name: Rust Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: build-binary
        path: target/debug/osm-import-indexer

    - uses: actions/upload-artifact@v2
      with:
        name: release-binary
        path: target/release/osm-import-indexer
