[package]
name = "osm-import-indexer"
version = "0.1.0"
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
protobuf = '3.0.2'
flate2 = "1.0.20"
geojson = "0.21.0"
serde_json = "1.0.64"

[build-dependencies]
protobuf-codegen-pure = "2.23.0"
