[package]
name = "osm-import-indexer"
version = "0.1.0"
authors = ["Matt Brown <matt@ederoyd.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
protobuf = '2.14.0'
flate2 = "1.0.14"
geojson = "0.18.0"
serde_json = "1.0.53"

[build-dependencies]
protobuf-codegen-pure = "2.14.0"
